apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "monitor-syscalls"
spec:
  kprobes:
  - call: "sys_openat"
    syscall: true
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "string"
    - index: 2
      type: "int"
    - index: 3
      type: "int"
  - call: "sys_connect"
    syscall: true
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "sockaddr"
    - index: 2
      type: "int"
