apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "monitor-syscalls"
spec:
  kprobes:
  - call: "sys_openat"
    syscall: true
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "string"
    - index: 2
      type: "int"
    - index: 3
      type: "int"
  - call: "sys_connect"
    syscall: true
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "sockaddr"
    - index: 2
      type: "int"
  - call: "sys_sendto"
    syscall: true
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "char_buf"
      sizeArgIndex: 2
    - index: 2
      type: "size_t"
    - index: 3
      type: "int"
    - index: 4
      type: "sockaddr"
    - index: 5
      type: "int"
